version: '3.8'

services:
  jobs:
    container_name: jobsApi
    build: ./jobs
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"  
    volumes:
      - ./jobs:/app
    environment:
      - JOB_DB_NAME=jobs
      - JOB_DB_USER=postgres
      - JOB_DB_PASSWORD=postgres
      - JOB_DB_HOST=jobsDB  
    depends_on:
      - jobsDB

  users:
    container_name: usersApi
    build: ./users
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"  
    volumes:
      - ./users:/app
    environment:
      - USERS_DB_NAME=users
      - USERS_DB_USER=postgres
      - USERS_DB_PASSWORD=postgres
      - USERS_DB_HOST=usersDB  
    depends_on:
      - usersDB

  blog:
    container_name: blogApi
    build: ./blog
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    ports:
      - "8003:8003"  
    volumes:
      - ./blog:/app
    environment:
      - BLOG_DB_NAME=blog
      - BLOG_DB_USER=postgres
      - BLOG_DB_PASSWORD=postgres
      - BLOG_DB_HOST=blogDB 
    depends_on:
      - blogDB

  jobsDB:
    image: postgres:15
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - jobs-data:/var/lib/postgresql/data

  usersDB:
    image: postgres:15
    ports:
      - "5433:5432"  
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - users-data:/var/lib/postgresql/data

  blogDB:
    image: postgres:15
    ports:
      - "5434:5432"  
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - blog-data:/var/lib/postgresql/data

volumes:
  jobs-data:
  users-data:
  blog-data:
